---
- name: Install helm
  become: true
  unarchive:
    src: "{{ helm_download_archive }}"
    dest: /usr/local/bin/
    include: [linux-amd64/helm]
    owner: root
    group: root
    remote_src: yes
    extra_opts:
     - --strip-components=1
  retries: 5
  delay: 5

- name: Install kubectl
  become: true
  get_url:
    url: "{{ kubectl_download_url }}"
    dest: /usr/local/bin
    mode: 0755

- name: Install k9s
  become: true
  unarchive:
    src: "{{ k9s_download_archive }}"
    dest: /usr/local/bin/
    include: [k9s]
    owner: root
    group: root
    remote_src: yes
  retries: 5
  delay: 5

- name: Install kustomize
  become: true
  unarchive:
    src: "{{ kustomize_download_archive }}"
    dest: /usr/local/bin/
    include: [kustomize]
    owner: root
    group: root
    remote_src: yes
  retries: 5
  delay: 5

# per https://github.com/johanhaleby/kubetail#installation
- name: Install kubetail
  become: true
  get_url:
    url: "{{ kubetail_download_url }}"
    dest: /usr/local/bin
    mode: 0755

# see https://cluster-api.sigs.k8s.io/user/quick-start.html#install-clusterctl
- name: Install clusterctl
  become: true
  get_url:
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/{{ capi_core_version }}/clusterctl-linux-amd64"
    dest: /usr/local/bin/clusterctl
    mode: 0755
    owner: root
    group: root
